name: Job - Run End-to-End Tests

on:
  workflow_call:
    inputs:
      aws-region:
        description: "AWS region to deploy to"
        type: string
        required: true
      oidc-role-arn:
        description: "OIDC role to assume"
        type: string
        required: true
      environment:
        description: "Environment to run tests against (e.g. stage, prod)"
        type: string
        required: true
      api-collection-dir:
        description: "Directory containing API collection files"
        type: string
        default: "API Collection"
      prod-tag:
        description: "Bruno tag used to filter tests when running against prod"
        type: string
        default: "prod-safe"

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.2
        with:
          role-to-assume: ${{ inputs.oidc-role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli@3.4.2

      - name: Run API collection for Prod
        if: inputs.environment == 'prod'
        working-directory: ${{ inputs.api-collection-dir }}
        run: bru run --env-var "envName=${{ inputs.environment }}" --tags ${{ inputs.prod-tag }}

      - name: Run API collection for Non-Prod
        if: inputs.environment != 'prod'
        working-directory: ${{ inputs.api-collection-dir }}
        run: bru run --env-var "envName=${{ inputs.environment }}"
