name: Pull Request

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use (e.g. 24)"
        type: string
        required: true
      aws-region:
        description: "AWS region to deploy to"
        type: string
        required: true
      oidc-role:
        description: "OIDC role to assume"
        type: string
        required: true
      cdk-stack-name:
        description: "Base name of the CDK stack"
        type: string
        required: true
      cdk-dir:
        description: "Directory containing CDK app"
        type: string
        default: "app-stack"
      api-collection-dir:
        description: "Directory containing API collection files"
        type: string
        default: "API Collection"

permissions:
  contents: read
  id-token: write

jobs:
  format_check:
    name: Check Formatting
    uses: ./.github/workflows/jobs/node/job.check-formatting.yml
    with:
      node-version: ${{ inputs.node-version }}

  unit_tests:
    name: Run Unit Tests
    uses: ./.github/workflows/jobs/node/job.run-unit-tests.yml
    with:
      node-version: ${{ inputs.node-version }}

  integration_tests:
    name: Run Integration Tests
    uses: ./.github/workflows/jobs/node/job.run-integration-tests.yml
    with:
      node-version: ${{ inputs.node-version }}

  deploy:
    name: Deploy to Feature Environment
    uses: ./.github/workflows/jobs/cdk/job.deploy-env.yml
    with:
      aws-region: ${{ inputs.aws-region }}
      oidc-role: ${{ inputs.oidc-role }}
      environment: pr-${{ github.event.pull_request.number }}
      node-version: ${{ inputs.node-version }}
      cdk-stack-name: ${{ inputs.cdk-stack-name }}
      cdk-dir: ${{ inputs.cdk-dir }}

  e2e_tests:
    name: Run E2E Tests on Feature Environment
    needs: [deploy]
    uses: ./.github/workflows/jobs/bruno/job.run-e2e-tests.yml
    with:
      aws-region: ${{ inputs.aws-region }}
      oidc-role: ${{ inputs.oidc-role }}
      environment: pr-${{ github.event.pull_request.number }}
      api-collection-dir: ${{ inputs.api-collection-dir }}
